### ISSUE TITLE
@HasTemplate complain <wicket:head> <wicket:extend> in HTML

### ISSUE THREAD

**Issue by ZengII** [neurolabs/wicket-id-bindings-generator#2]
@HasTemplate can't parse html file correct when there are wicket:head wicket:extend.
And then I can't get MyPageWID to use.

**Comment by neurolabs** [comment]
Could you please provide an error message and an example template that does not work?

First guess is that you probably need a wrapping html statement, e.g. 

```
<!DOCTYPE html>
<html xmlns:wicket="http://wicket.apache.org">
  <wicket:head>...</wicket:head>
  <wicket:extend>...</wicket:extend>
</html>
```

Can you try that and report on it?

Thanks

**Comment by neurolabs** [comment]
old and dusty
